# Generated by Django 4.0.6 on 2022-07-26 04:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('emp', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='employee',
            old_name='name',
            new_name='Empname',
        ),
        migrations.RenameField(
            model_name='employee',
            old_name='num',
            new_name='Empnum',
        ),
        migrations.RenameField(
            model_name='employee',
            old_name='add',
            new_name='address',
        ),
        migrations.RenameField(
            model_name='employee',
            old_name='sal',
            new_name='salary',
        ),
    ]
